GET https://localhost:8443//2018/wp-includes/wlwmanifest.xml
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:129.0) Gecko/20100101 Firefox/129.0
HTTP 418

GET https://localhost:8443//2019/wp-includes/wlwmanifest.xml
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:129.0) Gecko/20100101 Firefox/129.0
HTTP 418

GET https://localhost:8443//2020/wp-includes/wlwmanifest.xml
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:129.0) Gecko/20100101 Firefox/129.0
HTTP 418

GET https://localhost:8443//blog/wp-includes/wlwmanifest.xml
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:129.0) Gecko/20100101 Firefox/129.0
HTTP 418

GET https://localhost:8443//cms/wp-includes/wlwmanifest.xml
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:129.0) Gecko/20100101 Firefox/129.0
HTTP 418

GET https://localhost:8443//media/wp-includes/wlwmanifest.xml
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:129.0) Gecko/20100101 Firefox/129.0
HTTP 418

GET https://localhost:8443//news/wp-includes/wlwmanifest.xml
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:129.0) Gecko/20100101 Firefox/129.0
HTTP 418

GET https://localhost:8443//shop/wp-includes/wlwmanifest.xml
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:129.0) Gecko/20100101 Firefox/129.0
HTTP 418

GET https://localhost:8443//site/wp-includes/wlwmanifest.xml
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:129.0) Gecko/20100101 Firefox/129.0
HTTP 418

GET https://localhost:8443//sito/wp-includes/wlwmanifest.xml
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:129.0) Gecko/20100101 Firefox/129.0
HTTP 418

GET https://localhost:8443//test/wp-includes/wlwmanifest.xml
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:129.0) Gecko/20100101 Firefox/129.0
HTTP 418

GET https://localhost:8443//web/wp-includes/wlwmanifest.xml
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:129.0) Gecko/20100101 Firefox/129.0
HTTP 418

GET https://localhost:8443//website/wp-includes/wlwmanifest.xml
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:129.0) Gecko/20100101 Firefox/129.0
HTTP 418

GET https://localhost:8443//wordpress/wp-includes/wlwmanifest.xml
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:129.0) Gecko/20100101 Firefox/129.0
HTTP 418

GET https://localhost:8443//wp-includes/wlwmanifest.xml
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:129.0) Gecko/20100101 Firefox/129.0
HTTP 418

GET https://localhost:8443//wp/wp-includes/wlwmanifest.xml
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:129.0) Gecko/20100101 Firefox/129.0
HTTP 418

GET https://localhost:8443//wp1/wp-includes/wlwmanifest.xml
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:129.0) Gecko/20100101 Firefox/129.0
HTTP 418

GET https://localhost:8443//wp2/wp-includes/wlwmanifest.xml
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:129.0) Gecko/20100101 Firefox/129.0
HTTP 418

GET https://localhost:8443/wordpress/wp-admin/setup-config.php
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:129.0) Gecko/20100101 Firefox/129.0
HTTP 418

GET https://localhost:8443/wp-admin/setup-config.php
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:129.0) Gecko/20100101 Firefox/129.0
HTTP 418

