GET https://localhost:8443/lovelace
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:129.0) Gecko/20100101 Firefox/129.0
HTTP 200

# This is WSS which should be tested in future
# Currently no testing as it needs some extra backend code.
# GET wss://localhost:8443/api/websocket
# User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:129.0) Gecko/20100101 Firefox/129.0
# HTTP 200

GET https://localhost:8443/sw-modern.js
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:129.0) Gecko/20100101 Firefox/129.0
HTTP 200

GET https://localhost:8443/frontend_latest/13255.4EVdx_9MOD4.js
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:129.0) Gecko/20100101 Firefox/129.0
HTTP 200

GET https://localhost:8443/api/camera_proxy/camera.just_a_cam?authSig=h5TBq9jlqqv73h8jypq9DS60E0XFxh3g7ZAQES6JLCMuFvMDNtd/9ohQ+/W2qBTVHEUf6/Dhc+iiO06IvcFw/7I4E8a0Es1myHYg4eZX4f6Ew7MV+QOWpVRJ8dVtqHNz&width=980&height=552
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:129.0) Gecko/20100101 Firefox/129.0
Referer: https://localhost:8443/lovelace/0
HTTP 200

GET https://localhost:8444/lovelace
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:129.0) Gecko/20100101 Firefox/129.0
HTTP 200

# GET wss://localhost:8444/api/websocket
# User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:129.0) Gecko/20100101 Firefox/129.0
# HTTP 200

GET https://localhost:8444/sw-modern.js
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:129.0) Gecko/20100101 Firefox/129.0
HTTP 200

GET https://localhost:8444/frontend_latest/13255.4EVdx_9MOD4.js
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:129.0) Gecko/20100101 Firefox/129.0
HTTP 200

GET https://localhost:8444/api/camera_proxy/camera.just_a_cam?authSig=h5TBq9jlqqv73h8jypq9DS60E0XFxh3g7ZAQES6JLCMuFvMDNtd/9ohQ+/W2qBTVaHEUf6/Dhc+iiO06IvcFw/7I4E8a0Es1myHYg4eZX4f6Ew7MV+QOWpVRJ8dVtqHNz&width=980&height=552
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:129.0) Gecko/20100101 Firefox/129.0
Referer: https://localhost:8443/lovelace/0
HTTP 200

