GET https://localhost:8443/core/img/actions/share.svg
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:137.0) Gecko/20100101 Firefox/137.0
HTTP 404

GET https://localhost:8443/core/img/actions/settings-dark.svg
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:137.0) Gecko/20100101 Firefox/137.0
HTTP 404

GET https://localhost:8443/core/img/favicon.ico
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:137.0) Gecko/20100101 Firefox/137.0
HTTP 418

GET https://localhost:8443/core/img/favicon-touch.png
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:137.0) Gecko/20100101 Firefox/137.0
HTTP 418

GET https://localhost:8443/core/img/favicon-mask.svg
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:137.0) Gecko/20100101 Firefox/137.0
HTTP 418
