---
name: Test Nginx config on Ubuntu 20.04-24.04

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ubuntu_20_04_focal:
    uses: ./.github/workflows/reusable-test-nginx.yml
    with:
      container: "ubuntu:20.04"

  ubuntu_22_04_jammy:
    uses: ./.github/workflows/reusable-test-nginx.yml
    with:
      container: "ubuntu:22.04"

  ubuntu_24_04_mantic:
    uses: ./.github/workflows/reusable-test-nginx.yml
    with:
      container: "ubuntu:24.04"

